# Default values for uiweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deekshithsn/shoe
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: "shoe"

service:
  type: ClusterIP
  port: 1002

container: 
  port: 1002


