apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoe.fullname" . }}
  labels:
    {{- include "shoe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "shoe.selectorLabels" . | nindent 4 }}
